const estadoMetas = { periodo: "mes" };
const dinero = valor => BaluarteData.moneda(valor);
function fechaFactura(valor) { const p = String(valor || "").split("/").map(Number); if (p.length === 3 && p.every(Number.isFinite)) return new Date(p[2], p[1] - 1, p[0]); const f = new Date(valor); return Number.isNaN(f.getTime()) ? null : f; }
function inicioDia(f) { return new Date(f.getFullYear(), f.getMonth(), f.getDate()); }
function mismaFecha(a, b) { return a.getFullYear() === b.getFullYear() && a.getMonth() === b.getMonth() && a.getDate() === b.getDate(); }
function facturasPeriodo() { const hoy = inicioDia(new Date()); return BaluarteData.leer("facturas").filter(f => { const fecha = fechaFactura(f.fecha); if (!fecha) return estadoMetas.periodo === "todo"; if (estadoMetas.periodo === "todo") return true; if (estadoMetas.periodo === "semana") { const inicio = new Date(hoy); inicio.setDate(hoy.getDate() - 6); return fecha >= inicio && fecha <= hoy; } return fecha.getMonth() === hoy.getMonth() && fecha.getFullYear() === hoy.getFullYear(); }); }
function grafica(facturas) { const hoy = inicioDia(new Date()), dias = estadoMetas.periodo === "mes" ? Math.min(hoy.getDate(), 14) : 7; return Array.from({ length: dias }, (_, pos) => { const fecha = new Date(hoy); fecha.setDate(hoy.getDate() - (dias - 1 - pos)); return { fecha, total: facturas.filter(f => { const actual = fechaFactura(f.fecha); return actual && mismaFecha(actual, fecha); }).reduce((s, f) => s + Number(f.total || 0), 0) }; }); }
function renderizarMetas() {
    const facturas = facturasPeriodo(), config = BaluarteData.leer("configuracion", { metaMensual: 50000000 }), meta = Number(config.metaMensual || 0);
    const ventas = facturas.reduce((s, f) => s + Number(f.total || 0), 0), unidades = facturas.reduce((s, f) => s + (f.productos || []).reduce((n, p) => n + Number(p.cantidad || 0), 0), 0);
    const hoy = new Date(), diasMes = new Date(hoy.getFullYear(), hoy.getMonth() + 1, 0).getDate(), transcurridos = hoy.getDate(), restantes = Math.max(0, diasMes - transcurridos), porcentaje = meta ? Math.min(100, ventas / meta * 100) : 0, proyeccion = transcurridos ? ventas / transcurridos * diasMes : 0, faltante = Math.max(0, meta - ventas), diaria = faltante / Math.max(restantes, 1);
    document.getElementById("metaPorcentaje").textContent = `${Math.round(porcentaje)}%`; document.getElementById("metaDinero").textContent = dinero(ventas); document.getElementById("metaMensual").textContent = `Meta: ${dinero(meta)}`; document.getElementById("barraMeta").style.width = `${porcentaje}%`;
    document.getElementById("metaPlatillos").textContent = unidades.toLocaleString("es-CO"); document.getElementById("metaFacturas").textContent = facturas.length; document.getElementById("ticketPromedio").textContent = dinero(facturas.length ? ventas / facturas.length : 0); document.getElementById("metaDiaria").textContent = dinero(diaria); document.getElementById("diasRestantes").textContent = restantes ? `${restantes} días restantes del mes` : "Último día del mes";
    document.getElementById("proyeccionMensual").textContent = dinero(proyeccion); document.getElementById("detalleProyeccion").textContent = ventas ? `Promedio diario actual: ${dinero(ventas / transcurridos)}.` : "Registra ventas para estimar el cierre."; document.getElementById("estadoProyeccion").textContent = proyeccion >= meta && meta ? "Proyección favorable" : ventas ? "Aún por debajo de la meta" : "Sin datos";
    document.getElementById("faltanteMeta").textContent = dinero(faltante); document.getElementById("mensajeMeta").textContent = porcentaje >= 100 ? "¡Meta alcanzada! Excelente trabajo del equipo." : `Faltan ${dinero(faltante)} para llegar a la meta mensual.`; document.getElementById("detalleFaltante").textContent = porcentaje >= 100 ? "La meta fue alcanzada; cada venta adicional supera el objetivo." : `Se requieren aproximadamente ${dinero(diaria)} por día para cumplirla.`; document.getElementById("etiquetaPeriodo").textContent = estadoMetas.periodo === "mes" ? "Mes actual" : estadoMetas.periodo === "semana" ? "Últimos 7 días" : "Todo el historial";
    const datos = grafica(facturas), max = Math.max(...datos.map(d => d.total), 1); document.getElementById("totalGrafica").textContent = dinero(ventas); document.getElementById("graficaVentas").style.gridTemplateColumns = `repeat(${datos.length},1fr)`; document.getElementById("etiquetasGrafica").style.gridTemplateColumns = `repeat(${datos.length},1fr)`; document.getElementById("graficaVentas").innerHTML = datos.map(d => `<div class="barra-dia" title="${d.fecha.toLocaleDateString("es-CO")}: ${dinero(d.total)}"><span style="height:${Math.max(d.total ? 8 : 2, d.total / max * 100)}%"></span></div>`).join(""); document.getElementById("etiquetasGrafica").innerHTML = datos.map(d => `<span>${d.fecha.toLocaleDateString("es-CO", { day: "numeric", month: "short" })}</span>`).join("");
    const productos = {}; facturas.forEach(f => (f.productos || []).forEach(p => { const c = p.codigo || p.nombre; productos[c] = productos[c] || { nombre: p.nombre, cantidad: 0 }; productos[c].cantidad += Number(p.cantidad || 0); })); const ranking = Object.values(productos).sort((a,b) => b.cantidad - a.cantidad).slice(0, 4); document.getElementById("rankingProductos").innerHTML = ranking.length ? ranking.map((p,i) => `<li><span class="puesto">${i + 1}</span><span>${p.nombre}</span><strong>${p.cantidad} und.</strong></li>`).join("") : '<li class="sin-ranking">Aún no hay productos vendidos.</li>';
}
document.querySelectorAll(".periodo").forEach(b => b.addEventListener("click", () => { estadoMetas.periodo = b.dataset.periodo; document.querySelectorAll(".periodo").forEach(x => x.classList.toggle("activo", x === b)); renderizarMetas(); }));
const modalMeta = document.getElementById("modalMeta"); document.getElementById("btnEditarMeta").addEventListener("click", () => { document.getElementById("nuevaMeta").value = BaluarteData.leer("configuracion", { metaMensual: 50000000 }).metaMensual; modalMeta.showModal(); }); document.getElementById("cerrarMeta").addEventListener("click", () => modalMeta.close()); document.getElementById("cancelarMeta").addEventListener("click", () => modalMeta.close()); document.getElementById("formMeta").addEventListener("submit", e => { e.preventDefault(); const config = BaluarteData.leer("configuracion", {}); config.metaMensual = Number(document.getElementById("nuevaMeta").value); BaluarteData.guardar("configuracion", config); modalMeta.close(); renderizarMetas(); }); renderizarMetas();
